modLoader="javafml"
loaderVersion="[47,)"
license="All Rights Reserved"

[[mods]]
modId="batman_mod"
version="1.0.0"
displayName="Batman Mod"
credits="The_WereF0X"
displayURL="https://discord.gg/9uqXBM2Gus"
authors="The_WereF0X"

[[dependencies.batman_mod]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1]"
    ordering="NONE"
    side="BOTH"




